layout_spectrum: 0.05734767
typography_spectrum: 0.4390681
color:
  saturation: 0.401345
  lightness: 0.8400757
  brandStrength: 1
  brandColors:
    - '#4E74B5'
    - '#06070B'
    - '#D4C5A6'
    - '#9B6C5C'
    - '#FFFEFE'
  rhythmicContrast: 0.5286748
name: Adayinthelife
